(function(){function d(d,b,f,t){return isNaN(d)?b:d<f?f:d>t?t:d}function qa(d,b){for(var f={},t=1;4>t;t++){var E=d["wave"+t];if(E)for(var s in E)!isNaN(E[s])&&s in ra&&(f[ra[s]+t]=E[s])}if(b)for(s in Ia)s in f||(f[s]=0);return f}function N(M,b){function Z(a){m.width=y.clientWidth;m.height=y.clientHeight}function t(a,c,b){b=$/(aa+b);return{x:b*a,y:b*c,alpha:1>b?b*b:1,scale:b}}function E(){var a,b,d,e,f,k,h;O=Math.sqrt(z*z+A*A);n=z/O||1E-4;p=-A/O||1E-4;P=Math.sin(c.angle);F=Math.cos(c.angle);e=[[n*
    n+p*p*F,n*p*(1-F),p*P],[n*p*(1-F),p*p+n*n*F,-n*P],[-p*P,n*P,(n*n+p*p)*F]];h=q;var l=[],g;for(g=0;3>g;g++)for(l[g]=[],a=0;3>a;a++)l[g][a]=e[g][0]*h[0][a]+e[g][1]*h[1][a]+e[g][2]*h[2][a];q=l;m.width=m.width;U.fillStyle=ba;U.translate(m.width/2,m.height/2);for(l=ca;l--;)for(e=l/ca*V-Aa,g=h=Math.round(ca*Math.cos(e)*2);g--;)a=g/h*2*V-V,d=(Q+c.amp1*Math.sin(c.freq1*e+c.pha1))*Math.cos(e)*Math.cos(a),f=(Q+c.amp2*Math.sin(c.freq2*a+c.pha2))*Math.cos(e)*Math.sin(a),k=(Q+c.amp3*Math.sin(c.freq3*e+c.pha3))*
    Math.sin(e),a=q[0][0]*d+q[0][1]*f+q[0][2]*k,b=q[1][0]*d+q[1][1]*f+q[1][2]*k,d=q[2][0]*d+q[2][1]*f+q[2][2]*k,a=t(a,b,d),b=da*a.scale,U.globalAlpha=a.alpha,0<b&&U.fillRect(a.x,a.y,b,b)}function s(a){var b=m.getBoundingClientRect();return{x:a.clientX-b.left,y:a.clientY-b.top}}function ea(a){fa=(new Date).getTime();fa-sa>1E3/Ba&&(l=s(a),G=l.x-ga,H=l.y-ha,I=Math.sqrt(G*G+H*H),W=Math.sqrt((l.x-m.width/2)*(l.x-m.width/2)+(l.y-m.height/2)*(l.y-m.height/2)),I&&W<J&&(ia=W<u?1:(J-W)/(J-u),Math.abs(Math.acos((G*
    ta+H*ua)/(va*I)))>Math.PI/2&&(K*=-1),Math.min(I,wa)*B*ia>Math.abs(c.angle)&&(xa.stop(),c.angle=K*Math.min(I,wa)*B*ia,A=K*G,z=K*H,xa=Ca.run(c,{angle:K*X},f.powOut(3),ja,C)),ta=G,ua=H,va=I),ga=l.x,ha=l.y,sa=fa)}function R(a){document.removeEventListener("mousemove",R);l=s(a);ga=l.x;ha=l.y;document.addEventListener("mousemove",ea)}var ka=document.getElementById(M);if(ka){N.instances[M]&&N.instances[M].destroy();N.instances[M]=this;b||(b={});var e=Number.POSITIVE_INFINITY,Ba=30,wa=100,V=Math.PI,Aa=V/
    2,ca=d(b.DETALISATION,60,1,e),Q=d(b.BLOB_SIZE,220,1,e),S=d(b.BLOB_DISTANCE,1E3,0,e),X=d(b.ROTATION_SPEED,5,0,e)/1E3,v=d(b.PERSPECTIVE_DISTORTION,1,.001,e),da=d(b.DOT_SIZE,2,0,e),ba=b.DOT_COLOR||"black",u=d(b.MOUSE_DISTANCE_MIN,20,0,e),J=d(b.MOUSE_DISTANCE_MAX,u+400,u+.001,e),B=d(b.MOUSE_SENSITIVITY,1,0,e)/1E3,ja=1E3*d(b.INERTIAL_TIME,2,0,e),Da=b.INITIAL_SHAPE||{wave1:{amplitude:70,frequency:3,phase:0},wave2:{amplitude:60,frequency:2,phase:0},wave3:{amplitude:50,frequency:2,phase:0}},Y=b.USE_MORPHING,
    la=b.USE_WAVE_MOTION,ya=b.USE_WAVE_SWING,Ea="MORPHING_AUTOPLAY"in b?b.MORPHING_AUTOPLAY:!0,za=d(b.MORPHING_DURATION,2,0,e),Fa=d(b.MORPHING_DELAY,1,0,e),L=b.MORPHING_TRANSITION_TYPE||"cubic",g=b.MORPHING_SHAPES||[];if(la&&Y&&g.length)for(var r=1;4>r;r++)if(b["WAVE_"+r+"_MOTION_SPEED"])for(var k=g.length;k--;){var T=g[k]["wave"+r];T&&"phase"in T&&delete T.phase}if(ya)for(r=1;4>r;r++){var w=b["WAVE_"+r+"_SWING_SETTINGS"];if(w){for(var D in w){var h=w[D];if(h){if(Y)for(k=g.length;k--;)(T=g[k]["wave"+
    r])&&D in T&&delete T[D];"type"in h&&(h.wave=("function"===typeof h.type?h.type:Ja[h.type])||ma.sin,delete h.type);"amplitude"in h&&isNaN(h.amplitude)&&delete h.amplitude;"frequency"in h&&isNaN(h.frequency)&&delete h.frequency;"phase"in h&&isNaN(h.phase)&&delete h.phase}}w.phase&&la&&(b["WAVE_"+r+"_MOTION_SPEED"]=0)}}var na=b.WAVE_1_MOTION_SPEED,oa=b.WAVE_2_MOTION_SPEED,pa=b.WAVE_3_MOTION_SPEED,aa=S/v,$=1E3/v,y=function(){var a=document.createElement("div");Ga.set(a,{position:"relative",width:"100%",
    height:"100%",top:0,left:0,margin:0,userSelect:"none",MozUserSelect:"none",WebkitUserSelect:"none",MsUserSelect:"none",KhtmlUserSelect:"none",userDrag:"none",WebkitUserDrag:"none",overflow:"hidden",cursor:"default"});a.setAttribute("unselectable","on");ka.appendChild(a);return a}(),m=function(){var a=document.createElement("canvas");Ga.set(a,{position:"absolute",width:"100%",height:"100%",top:0,left:0,margin:0});a.width=y.clientWidth;a.height=y.clientHeight;y.appendChild(a);return a}(),U=m.getContext("2d"),
    C=new Ka,c=function(){var a={set:function(a){for(var b in a)this[b]=a[b]},angle:X},b=qa(Da,!0),c;for(c in b)a[c]=b[c];return a}(),A=5,z=5,K=1,xa={stop:function(){}},P=Math.sin(c.angle),F=Math.cos(c.angle),O=Math.sqrt(z*z+A*A),n=z/O,p=-A/O,q=[[1,0,0],[0,1,0],[0,0,1]],W,ia,l,ta=0,ua=0,va=0,G,H,I,ga,ha,fa,sa=(new Date).getTime(),x;this.resize=function(){Z()};this.destroy=function(){N.instances[M]=null;C.removeAllListeners();x&&x.clear();window.removeEventListener("resize",Z);document.removeEventListener("mousemove",
    R);document.removeEventListener("mousemove",ea);y.removeChild(m);ka.removeChild(y);ka=M=b=e=Ba=wa=V=Aa=ca=Q=X=v=da=ba=u=J=B=ja=Da=Y=la=ya=Ea=za=Fa=L=g=na=oa=pa=S=aa=$=y=m=U=C=c=A=z=K=xa=P=F=O=n=p=q=W=ia=l=ta=ua=va=G=H=I=ga=ha=fa=sa=x=Z=t=E=s=ea=R=null;for(D in this)delete this[D];this.resize=this.destroy=this.morphTo=function(){}};this.morphTo=function(a){if(Y&&g.length){var b;a&&"object"===typeof a?b=a:!isNaN(a)&&0<=a&&a<g.length&&!(a-Math.floor(a))&&(b=g[a]);b&&Ca.run(c,qa(b),"function"===typeof L?
    L:Ha[L],1E3*za,C)}};Object.defineProperties(this,{blobSize:{get:function(){return Q},set:function(a){Q=d(a,220,1,e)},configurable:!0},blobDistance:{get:function(){return S},set:function(a){S=d(a,1E3,0,e);aa=S/v;$=1E3/v},configurable:!0},rotationSpeed:{get:function(){return X},set:function(a){c.angle=X=d(a,5,0,e)/1E3},configurable:!0},perspectiveDistortion:{get:function(){return v},set:function(a){v=d(a,1,.001,e);aa=S/v;$=1E3/v},configurable:!0},dotSize:{get:function(){return da},set:function(a){da=
    d(a,2,0,e)},configurable:!0},dotColor:{get:function(){return ba},set:function(a){ba=a||"black"},configurable:!0},mouseDistanceMin:{get:function(){return u},set:function(a){u=d(a,20,0,J-1E-4)},configurable:!0},mouseDistanceMax:{get:function(){return J},set:function(a){J=d(a,u+400,u+.001,e)},configurable:!0},mouseSensitivity:{get:function(){return B},set:function(a){var b=B;(B=d(a,1,0,e)/1E3)&&!b?document.addEventListener("mousemove",R):b&&!B&&(document.removeEventListener("mousemove",R),document.removeEventListener("mousemove",
    ea))},configurable:!0},inertialTime:{get:function(){return ja},set:function(a){ja=1E3*d(a,2,0,e)},configurable:!0},wave1Amplitude:{get:function(){return c.amp1},set:function(a){c.amp1=a},configurable:!0},wave2Amplitude:{get:function(){return c.amp2},set:function(a){c.amp2=a},configurable:!0},wave3Amplitude:{get:function(){return c.amp3},set:function(a){c.amp3=a},configurable:!0},wave1Frequency:{get:function(){return c.freq1},set:function(a){c.freq1=a},configurable:!0},wave2Frequency:{get:function(){return c.freq2},
    set:function(a){c.freq2=a},configurable:!0},wave3Frequency:{get:function(){return c.freq3},set:function(a){c.freq3=a},configurable:!0},wave1Phase:{get:function(){return c.pha1},set:function(a){c.pha1=a},configurable:!0},wave2Phase:{get:function(){return c.pha2},set:function(a){c.pha2=a},configurable:!0},wave3Phase:{get:function(){return c.pha3},set:function(a){c.pha3=a},configurable:!0}});window.addEventListener("resize",Z);if(Y&&Ea&&g.length){x=new La;x.delay=Fa;k=0;for(w=g.length;k<w;k++)x.addTween(c,
    qa(g[k]),"function"===typeof L?L:Ha[L],za,C);x.addQueue(x);x.run()}la&&(k=function(){var a={},b=0;na&&!isNaN(na)&&(a.pha1=na,b++);oa&&!isNaN(oa)&&(a.pha2=oa,b++);pa&&!isNaN(pa)&&(a.pha3=pa,b++);return b?new Ma(c,a,C):0}())&&k.play();if(ya)for(k=1;4>k;k++)if(w=b["WAVE_"+k+"_SWING_SETTINGS"])for(D in w)(r=ra[D])&&(new Na(c,r+k,w[D],C)).play();C.addListener(E);B&&document.addEventListener("mousemove",R)}else alert("BlobAnimation ERROR: There is no element with the specified id")}var Ka=jsband.Metronome,
    f=jsband.Ease,Ca=jsband.Tween,Ga=jsband.CssProp,La=jsband.Queue,Na=jsband.Swing,ma=jsband.Wave,Ma=jsband.Motion,Ha={linear:f.lin(),quad:f.pow(2),cubic:f.pow(3),quart:f.pow(4),quint:f.pow(5),circ:f.circ(),sine:f.sin(),expo:f.exp(),elastic:f.osc2Out(),bounce:f.bncOut(),back:f.backOut()},Ja={sine:ma.sin,linear:ma.triangle,pulse:ma.pulse},Ia={amp1:1,freq1:1,pha1:1,amp2:1,freq2:1,pha2:1,amp3:1,freq3:1,pha3:1},ra={amplitude:"amp",frequency:"freq",phase:"pha"};N.instances={};window.hasOwnProperty("BlobAnimation")?
    alert('Unable to load "blob.js". Make sure that the document does not contain a global variable with the name "BlobAnimation"'):window.BlobAnimation=N})();
    